### ISSUE TITLE
Using LiveOak on OpenShift - apps are having issues

### ISSUE THREAD

**Issue by justbane** [liveoak-io/liveoak-example-auth-html#2]
Trying to setuo the Auth example from the example apps.

Follwed instructions in README - when accessing the ap I get this request error in my browser console.

.
liveoak.js:591 GET https://cuedata-baneville.rhcloud.com/auth/realms/liveoak-apps/login-status…nt.auth-html.auth-html-client&origin=https://cuedata-baneville.rhcloud.com 400 (Bad Request)
liveoak.js:591setupCheckLoginIframe
liveoak.js:80processInit
liveoak.js:544p.promise.success
liveoak.js:103kc.init
(index):90(anonymous function)

**Comment by justbane** [comment]
Inspecting the request reveals a message of "Invalid Origin"

I am 2 for 2 in example apps not working in this system... is this even maintained any longer? Really nice app if anything worked.

**Comment by kenfinnigan** [comment]
Sorry you've had some problems, last time I tested them it worked fine.

This week I'm releasing 1.0.0.Final and updating the OpenShift cartridge, so will make sure everything is working properly with it.

There may have been some changes since the version being used in the Cartridge, as it was not updated at the last release, that make it incompatible.

**Comment by justbane** [comment]
OK - figured out that its an issue of http vs https - for some reason even copy pating the urls in the liveoak client interface will remove the https... but all the links in the system go to https.

Now I get the auth html page as normal...but when I click login... I get the green LiveOak screen that says we're sorry - Invalid redirect_uri.

So yet again - seems broke... any help would be great

**Comment by kenfinnigan** [comment]
Ah ok, yes I believe the cartridge was updated to use https for all URLs.

Can you confirm that the redirect url specified for the client is your host (with https) followed by "auth-html/*"?

**Comment by justbane** [comment]
Ah that would be great kenfinnigan! Sorry I really love the application so far - its exactly what I am looking for but I think the documentation is a bit lacking.

I am planning on using it as a backend for an IOS app in Swift - are thee any resoirces you know of that might help me perform the login stuff in SWIFT? Honestly the login stuff is what I am having the most issue with.

**Comment by kenfinnigan** [comment]
To perform auth with Swift, there are libraries provided by AeroGear (https://aerogear.org/ios/) to handle that

**Comment by justbane** [comment]
Awesome - thank you!

**Comment by kenfinnigan** [comment]
Were you able to resolve the redirect url problem?

**Comment by kenfinnigan** [comment]
Glad to help, let me know if there's anything else I can do

**Comment by justbane** [comment]
No I wasn't able to resolve the redirect url issue - Not sure whats going there. Any ideas?

**Comment by kenfinnigan** [comment]
in the configuration for the application client, does the redirect url you defined have /* on the end of it?

From the encoded url it looks like it only has a forward slash, and is missing the wildcard

**Comment by justbane** [comment]
Bingo that was it, thanks for then help - I may never have seen that :/

**Comment by justbane** [comment]
One more question - the login/register screen, are these customizable? I mean the functionality is awesome can they be redesigned/customized or should they be rewritten in some way in your app?

Last question I promise

**Comment by kenfinnigan** [comment]
Glad that solved it, I know how frustrating getting security configuration right can be.

The way that works is LiveOak provides a "theme" which is then used by Keycloak to serve up the login/register screens.

It is possible to replace the LiveOak theme with a completely different one, which would be applied to the admin console and all applications on that instance that provide a login/register screen.

Last time I spoke with them, Keycloak does not provide the ability to use a separate theme for each application.

**Comment by justbane** [comment]
Understood, Thanks!

**Comment by kenfinnigan** [comment]
Glad to help
